name: Eleventy Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/setup-node@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        env:
          PUBLISH_DIR: ./_site 
          PUBLISH_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
